openapi: 3.0.2
info:
  title: piqraiz API document
  description: |-
    <b>API仕様書</b><br>
  version: 1.0.0
servers:
  - url: http://localhost:8000/
tags:
  - name: auth
    description: 認証関連
  - name: todo
    description: todo関連
paths:
  /todo:
    get:
      tags:
        - todo
      summary: todo取得
      description: ログインユーザのtodo listを取得
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/todoGetResponse'
    post:
      tags:
        - todo
      summary: todo追加
      description:
        ログインユーザのtodoを追加
      requestBody:
        description: request.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/todoPostRequest'
        required: true
      responses:
        201:
          description: A successful response.
      x-codegen-request-body-name: body

    put:
      tags:
        - todo
      summary: todo編集
      description:
        ログインユーザのtodoを編集
      requestBody:
        description: request.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/todoPutRequest'
        required: true
      responses:
        204:
          description: A successful response.
      x-codegen-request-body-name: body
    patch:
      tags:
        - todo
      summary: todoをdoneに
      description:
        ログインユーザのtodoをdoneにする
      requestBody:
        description: request.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/todoPatchRequest'
        required: true
      responses:
        204:
          description: A successful response.
      x-codegen-request-body-name: body
  /todo/{id}:
    delete:
      tags:
        - todo
      summary: todo削除
      description:
        ログインユーザのtodoを削除
      parameters:
        - name: id
          in: path
          description: pk
          required: true
          schema:
            type: integer
      responses:
        204:
          description: A successful response.
      x-codegen-request-body-name: body
components:
  schemas:
    todoGetResponse:
      type: array
      description: todoリスト
      items:
        $ref: '#/components/schemas/todoList'
    todoPostRequest:
      type: object
      $ref: '#/components/schemas/todoList'
    todoPutRequest:
      type: object
      $ref: '#/components/schemas/todoList'
    todoPatchRequest:
      type: object
      properties:
        id:
          type: string
          description: pk
    todoList:
      type: object
      properties:
        id:
          type: integer
          description: pk
        sort_id:
          type: integer
          description: 表示順序
        title:
          type: string
          description: タイトル
        content:
          type: string
          description: 内容
        has_done:
          type: boolean
          description: doneフラグ
        date:
          type: string
          format: date
          example: "2021/09/20"
        priority:
          type: integer
          description: 優先度
